create table street_uploads (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  street_name text not null,
  city text not null,
  country text not null,
  gps_lat double precision,
  gps_lon double precision,
  image_url text not null,
  notes text,
  created_at timestamp with time zone default now(),
  status text default 'pending' -- pending, verified, rejected
);

create table street_verifications (
  id bigint generated by default as identity primary key,
  upload_id bigint references street_uploads not null,
  verifier_id uuid references auth.users not null,
  vote boolean not null, -- true = approve, false = reject
  created_at timestamp with time zone default now()
);
