create table subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  status text not null, -- active, cancelled
  created_at timestamp with time zone default now()
);
